[build-system]
requires = ['numpy (>=1.8)', 'torch (>=1.10)','scipy (>=1.7.1)','qiskit (>=0.43.0)']

[project]
name = "tqix"
authors = [{name = "Binho Le", email = "binho@fris.tohoku.ac.jp"}]
dynamic = ["version", "description"]
